/**
 * @sw-package discovery
 */

HeyFrame.Service('privileges').addPrivilegeMappingEntry({
    category: 'permissions',
    parent: null,
    key: 'channel',
    roles: {
        viewer: {
            privileges: [
                'channel:read',
                'channel_type:read',
                HeyFrame.Service('privileges').getPrivileges('payment.viewer'),
                'shipping_method:read',
                'country:read',
                'currency:read',
                'channel_domain:read',
                'snippet_set:read',
                'channel_analytics:read',
                'product_export:read',
                'theme:read',
                'custom_field_set:read',
                'custom_field:read',
                'custom_field_set_relation:read',
                'category:read',
                'customer_group:read',
                HeyFrame.Service('privileges').getPrivileges('media.viewer'),
                'product_export:read',
                'product_stream:read',
                'product_visibility:read',
                'user_config:read',
                'user_config:create',
                'user_config:update',
                HeyFrame.Service('privileges').getPrivileges('measurement.viewer'),
            ],
            dependencies: [],
        },
        editor: {
            privileges: [
                'channel:update',
                'channel_analytics:create',
                'channel_analytics:delete',
                'channel_analytics:update',
                'channel_country:create',
                'channel_country:delete',
                'channel_country:update',
                'channel_currency:create',
                'channel_currency:delete',
                'channel_currency:update',
                'channel_domain:create',
                'channel_domain:delete',
                'channel_domain:update',
                'channel_language:create',
                'channel_language:delete',
                'channel_language:update',
                'channel_payment_method:create',
                'channel_payment_method:delete',
                'channel_payment_method:update',
                'channel_shipping_method:create',
                'channel_shipping_method:delete',
                'channel_shipping_method:update',
                'theme_channel:create',
                'theme_channel:delete',
                'product_export:create',
                'product_export:update',
                'product_visibility:create',
                'product_visibility:delete',
                'system_config:update',
            ],
            dependencies: ['channel.viewer'],
        },
        creator: {
            privileges: [
                'product_stream:read',
                'channel:create',
                'product_export:create',
                'product_export:update',
            ],
            dependencies: [
                'channel.viewer',
                'channel.editor',
            ],
        },
        deleter: {
            privileges: [
                'channel:delete',
                'product_visibility:delete',
            ],
            dependencies: ['channel.viewer'],
        },
    },
});
