framework:
  http_cache:
    enabled: true
  session:
    name: 'session-'
    handler_id: ~
    cookie_secure: 'auto'
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
  serializer: { enabled: true }
  secret: "%env(APP_SECRET)%"
  profiler:
    collect_serializer_data: true
  property_info:
    with_constructor_extractor: true
  default_locale:  zh_CN
  cache:
    prefix_seed: "%kernel.cache.hash%"
    app: cache.adapter.filesystem
    pools:
      cache.object:
        default_lifetime: 172800
        adapter: cache.app
        tags: cache.tags
      cache.http:
        default_lifetime: 172800
        adapter: cache.app
        tags: cache.tags
      cache.tags:
        adapter: cache.app
      cache.rate_limiter:
        adapter: cache.app
  messenger:
    failure_transport: failed
    serializer:
      default_serializer: messenger.transport.symfony_serializer
      symfony_serializer:
        format: json
        context: { }
    transports:
      failed: "%env(MESSENGER_TRANSPORT_FAILURE_DSN)%"
      async:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        serializer: messenger.transport.symfony_serializer
        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2
          max_delay: 0
      low_priority:
        dsn: "%env(MESSENGER_TRANSPORT_LOW_PRIORITY_DSN)%"
        serializer: messenger.transport.symfony_serializer
        retry_strategy:
          max_retries: 3
          delay: 1000
          multiplier: 2
          max_delay: 0
    buses:
      messenger.bus.default:
        middleware:
          - HeyFrame\Core\Framework\Adapter\Messenger\Middleware\QueuedTimeMiddleware
    routing:
      'HeyFrame\Core\Framework\MessageQueue\AsyncMessageInterface': async
      'HeyFrame\Core\Framework\MessageQueue\LowPriorityMessageInterface': low_priority
      'Symfony\Component\Mailer\Messenger\SendEmailMessage': async