name: 'Split Repository'

on:
  push:
    branches:
      - '*'
    paths:
      - src/Administration/**/*
      - src/Core/**/*
      - src/Frontend/**/*
      - src/Elasticsearch/**/*
      - src/Uni/**/*

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          -
            local_path: 'Administration'
            split_repository: 'administration'
          -
            local_path: 'Core'
            split_repository: 'core'
          -
            local_path: 'Frontend'
            split_repository: 'frontend'
          -
            local_path: 'Elasticsearch'
            split_repository: 'elasticsearch'
          -
            local_path: 'Uni'
            split_repository: 'uni'
          -
            local_path: 'Uni/Resources/app/uni'
            split_repository: 'heyuni'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Split package
        uses: symplify/monorepo-split-github-action@v12
        with:
          # 子目录路径
          package_directory: 'src/${{ matrix.package.local_path }}'

          # 推送目标仓库
          repository_organization: 'heyframe'
          repository_name: '${{ matrix.package.split_repository }}'

          # 当前分支
          branch: '${{ github.ref_name }}'

          # 签名用户
          user_name: "gxiaosong"
          user_email: "lyricsong47@gmail.com"
